version: "3"
services:
  news:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: news_app
    platform: linux/amd64
    depends_on:
      - mysql
    ports:
      - "9993:9993"
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
    ports:
      - '3306:3306'
    expose:
      - '3306'

