package models

import "time"

type Data struct {
	Uuid        string `json:"uuid"`
	Headline    string `json:"headline"`
	Description string `json:"description"`
	Keywords    string `json:"keywords"`
	Snippet     string `json:"snippet"`
	Url         string `json:"url"`
	//SimilarNews struct {
	//	Uuid        string `json:"uuid"`
	//	Headline    string `json:"headline"`
	//	Description string `json:"description"`
	//}
}

//type SimilarNews struct {
//	Uuid        string `json:"uuid"`
//	Headline    string `json:"headline"`
//	Description string `json:"description"`
//	Keywords    string `json:"keywords"`
//	Snippet     string `json:"snippet"`
//	Url         string `json:"url"`
//}

type AutoGenerated struct {
	Meta struct {
		Found    int `json:"found"`
		Returned int `json:"returned"`
		Limit    int `json:"limit"`
		Page     int `json:"page"`
	} `json:"meta"`
	Data []struct {
		UUID           string      `json:"uuid"`
		Title          string      `json:"title"`
		Description    string      `json:"description"`
		Keywords       string      `json:"keywords"`
		Snippet        string      `json:"snippet"`
		URL            string      `json:"url"`
		ImageURL       string      `json:"image_url"`
		Language       string      `json:"language"`
		PublishedAt    time.Time   `json:"published_at"`
		Source         string      `json:"source"`
		Categories     []string    `json:"categories"`
		RelevanceScore interface{} `json:"relevance_score"`
	} `json:"data"`
}
